### ISSUE TITLE
Do you know about process.env or .gitignore?

### ISSUE THREAD

**Issue by PinkQween** [vOlive-io/DungeonDwellers#1]
I just noticed if I tried to login to the admin I can probably access, that is the most simple solution. Still not secure and I could access being public. You should really use a server.

If you want a secure implementation please contact me at: hanna@hannaskairipa.com or +1 (970) 691-7604

**Comment by vOlive-io** [comment]
It's all good, this is just a setup button. I am going to add Google Sign up instead of this.
